/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/calculator": {
    /** @description Get all calculations */
    get: operations["getAllCalculations"];
    /** @description Create a calculation */
    post: operations["createCalculation"];
  };
  "/calculator/{id}": {
    /** @description Get calculation by ID */
    get: operations["getCalculationById"];
    /** @description Update a calculation */
    put: operations["updateCalculation"];
    /** @description Delete calculation by ID */
    delete: operations["deleteCalculationById"];
  };
  "/health": {
    /** @description Health check endpoint for Calculator API */
    get: operations["healthCheck"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Calculation command */
    CalculatorCommand: {
      /** @enum {string} */
      operator: "+" | "-" | "*" | "/";
      operand1: number;
      operand2: number;
    };
    /** @description Calculation result */
    CalculatorResult: components["schemas"]["CalculatorCommand"] & {
      /** @description Unique ID of the calculation */
      id: string;
      result?: number;
      message?: string;
      /**
       * @description Number of milliseconds since Epoch time
       * @example 1688612539479
       */
      timestamp: number;
    };
    ErrorModel: {
      message: string;
    };
    /** @description Health check status */
    HealthStatus: {
      /** @enum {string} */
      status: "OK";
      /**
       * @description Number of milliseconds since Epoch time
       * @example 1688612539479
       */
      timestamp: number;
    };
  };
  responses: {
    /** @description Internal server error */
    InternalServerError: {
      content: {
        "application/json": components["schemas"]["ErrorModel"];
      };
    };
    /** @description Not found error */
    NotFoundError: {
      content: {
        "application/json": components["schemas"]["ErrorModel"];
      };
    };
  };
  parameters: {
    /** @description Calculator ID */
    CalculatorId: string;
  };
  requestBodies: {
    /** @description Calculator command request body */
    CalculatorCommand: {
      content: {
        "application/json": components["schemas"]["CalculatorCommand"];
      };
    };
  };
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** @description Get all calculations */
  getAllCalculations: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CalculatorResult"][];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  /** @description Create a calculation */
  createCalculation: {
    requestBody: components["requestBodies"]["CalculatorCommand"];
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["CalculatorResult"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
  /** @description Get calculation by ID */
  getCalculationById: {
    parameters: {
      path: {
        id: components["parameters"]["CalculatorId"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CalculatorResult"];
        };
      };
      404: components["responses"]["NotFoundError"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** @description Update a calculation */
  updateCalculation: {
    parameters: {
      path: {
        id: components["parameters"]["CalculatorId"];
      };
    };
    requestBody: components["requestBodies"]["CalculatorCommand"];
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CalculatorResult"];
        };
      };
      404: components["responses"]["NotFoundError"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** @description Delete calculation by ID */
  deleteCalculationById: {
    parameters: {
      path: {
        id: components["parameters"]["CalculatorId"];
      };
    };
    responses: {
      /** @description Deleted */
      204: never;
      404: components["responses"]["NotFoundError"];
      500: components["responses"]["InternalServerError"];
    };
  };
  /** @description Health check endpoint for Calculator API */
  healthCheck: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["HealthStatus"];
        };
      };
      500: components["responses"]["InternalServerError"];
    };
  };
}
